const curriculum=[
 {unit:'第一单元 · 阅读',goal:'借助图片了解课文内容',lessons:['1 小蝌蚪找妈妈','2 我是什么','3 植物妈妈有办法','语文园地一','快乐读书吧：读读童话故事']},
 {unit:'第二单元 · 识字',goal:'发现汉字规律，积累词语',lessons:['1 场景歌','2 树之歌','3 拍手歌','4 田家四季歌','语文园地二']},
 {unit:'第三单元 · 阅读',goal:'对感兴趣的内容说出感受或想法',lessons:['4 彩虹','5 去外婆家','6 数星星的孩子','语文园地三']},
 {unit:'第四单元 · 阅读',goal:'联系上下文和生活经验理解词句',lessons:['7 古诗二首：登鹳雀楼、望庐山瀑布','8 黄山奇石','9 日月潭','10 葡萄沟','语文园地四']},
 {unit:'第五单元 · 阅读',goal:'初步体会课文讲述的道理',lessons:['11 坐井观天','12 寒号鸟','13 我要的是葫芦','语文园地五']},
 {unit:'第六单元 · 阅读',goal:'学习默读，了解人物故事',lessons:['14 八角楼上','15 朱德的扁担','16 难忘的泼水节','17 刘胡兰','语文园地六']},
 {unit:'第七单元 · 阅读',goal:'展开想象，感受自然之美',lessons:['18 古诗二首：敕勒歌、江雪','19 雾在哪里','20 雪孩子','语文园地七']},
 {unit:'第八单元 · 阅读',goal:'综合运用多种方法自主识字',lessons:['21 称赞','22 纸船和风筝','23 快乐的小河','语文园地八']}
];
const words=[['鹳雀楼','guàn què lóu','旧址在山西永济县，楼高三层，前对中条山，下临黄河。'],['白日','bái rì','太阳。'],['依','yī','依傍、靠着。'],['欲','yù','想要得到某种东西或达到某种目的的愿望。'],['尽','jìn','消失；这里指太阳落山。'],['穷','qióng','尽，使达到极点。'],['千里目','qiān lǐ mù','眼界宽阔，能看到很远的地方。'],['更','gèng','再。']];
const quiz=[['“白日依山尽”中的“依”是什么意思？',['太阳','依傍、靠着','消失'],'依傍、靠着'],['想看到更远的风景，应该怎么做？',['再登上一层楼','马上回家','大声唱歌'],'再登上一层楼'],['《登鹳雀楼》的作者是谁？',['王之涣','李白','杜甫'],'王之涣']];
let learned=JSON.parse(localStorage.getItem('yuwen-learned')||'[]'),index=0,quizIndex=0;
const view=document.querySelector('#studyView');
function save(){localStorage.setItem('yuwen-learned',JSON.stringify(learned));updateProgress()}
function updateProgress(){const n=learned.length;document.querySelector('#progressText').textContent=`${n} / 23`;document.querySelector('#progressBar').style.width=`${Math.min(n/23*100,100)}%`}
function renderCurriculum(){document.querySelector('#curriculumList').innerHTML=curriculum.map((u,i)=>`<details class="unit-item" ${i===0?'open':''}><summary><span><b>${u.unit}</b><small>${u.goal}</small></span><em>${u.lessons.length} 项</em></summary><div class="unit-lessons">${u.lessons.map(l=>`<button class="lesson-link" data-lesson="${l}"><span>${l}</span><i>›</i></button>`).join('')}</div></details>`).join('');document.querySelectorAll('.lesson-link').forEach(b=>b.onclick=()=>lessonView(b.dataset.lesson))}
function lessonView(title){const isPoem=title.includes('登鹳雀楼');view.innerHTML=`<div class="study-title"><h3>${title}</h3><span class="counter">预习任务卡</span></div><div class="lesson-intro"><div class="lesson-badge">今日预习</div><p>先读一遍课题，看看插图或课本页面，想一想：这节课讲了谁、什么事？</p><div class="prep-step"><b>① 读课题</b><span>把课题读清楚，圈出不认识的字。</span></div><div class="prep-step"><b>② 看重点</b><span>从课本中找出人物、地点或事情。</span></div><div class="prep-step"><b>③ 说一说</b><span>用自己的话说说你最想知道的问题。</span></div></div><div class="actions"><button class="primary" id="lessonDone">${learned.includes('l'+title)?'✓ 已完成':'完成本课预习'}</button>${isPoem?'<button class="secondary" id="openPoem">进入古诗卡片</button>':''}</div>`;document.querySelector('#lessonDone').onclick=()=>{if(!learned.includes('l'+title))learned.push('l'+title);save();lessonView(title)};if(isPoem)document.querySelector('#openPoem').onclick=()=>show('poem')}
function wordsView(){const [word,pinyin,definition]=words[index],done=learned.includes('w'+index);view.innerHTML=`<div class="study-title"><h3>生字词卡片</h3><span class="counter">${index+1} / ${words.length}</span></div><div class="flashcard"><div class="character">${word}</div><div class="pinyin">${pinyin}</div><div class="definition">${definition}</div></div><div class="actions"><button class="secondary" id="prev">← 上一个</button><button class="primary" id="know">${done?'✓ 已掌握':'我会了！'}</button><button class="secondary" id="next">下一个 →</button></div>`;document.querySelector('#prev').onclick=()=>{index=(index+words.length-1)%words.length;wordsView()};document.querySelector('#next').onclick=()=>{index=(index+1)%words.length;wordsView()};document.querySelector('#know').onclick=()=>{if(!learned.includes('w'+index))learned.push('w'+index);save();wordsView()}}
function poemView(){view.innerHTML=`<div class="study-title"><h3>《登鹳雀楼》古诗朗读</h3><span class="counter">唐 · 王之涣</span></div><div class="poem-text"><span class="poem-title">登鹳雀楼</span>白日依山尽<br>黄河入海流<br>欲穷千里目<br>更上一层楼</div><div class="actions"><button class="primary" id="poemDone">${learned.includes('poem')?'✓ 我读过了':'我读一遍了！'}</button></div>`;document.querySelector('#poemDone').onclick=()=>{if(!learned.includes('poem'))learned.push('poem');save();poemView()}}
function meaningView(){view.innerHTML=`<div class="study-title"><h3>诗意小讲堂</h3><span class="counter">读懂每一句</span></div>${[['白日依山尽','太阳依傍着山慢慢落下去了。'],['黄河入海流','黄河水朝着大海奔流而去。'],['欲穷千里目','想要看到千里以外的风光。'],['更上一层楼','那就要再登上一层高楼。']].map(x=>`<div class="meaning-row"><b>${x[0]}</b><br>${x[1]}</div>`).join('')}<div class="actions"><button class="primary" id="meaningDone">${learned.includes('meaning')?'✓ 我明白了':'我明白了！'}</button></div>`;document.querySelector('#meaningDone').onclick=()=>{if(!learned.includes('meaning'))learned.push('meaning');save();meaningView()}}
function quizView(){const q=quiz[quizIndex];view.innerHTML=`<div class="study-title"><h3>小小挑战</h3><span class="counter">第 ${quizIndex+1} / ${quiz.length} 题</span></div><div class="quiz-question">${q[0]}</div><div class="quiz-options">${q[1].map(o=>`<button data-answer="${o}">${o}</button>`).join('')}</div>`;document.querySelectorAll('.quiz-options button').forEach(btn=>btn.onclick=()=>{const correct=btn.dataset.answer===q[2];btn.classList.add(correct?'correct':'wrong');if(correct&&!learned.includes('q'+quizIndex))learned.push('q'+quizIndex);save();setTimeout(()=>{quizIndex=(quizIndex+1)%quiz.length;quizView()},650)})}
function show(section){document.querySelectorAll('.lesson-card').forEach(x=>x.classList.toggle('active',x.dataset.section===section));({words:wordsView,poem:poemView,meaning:meaningView,quiz:quizView}[section])()}
document.querySelectorAll('.lesson-card').forEach(x=>x.onclick=()=>show(x.dataset.section));document.querySelector('#resetProgress').onclick=()=>{if(confirm('要重新开始今天的预习吗？')){learned=[];save();show('words')}};renderCurriculum();updateProgress();show('words');if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
