const words=[['鹳雀楼','guàn què lóu','旧址在山西永济县，楼高三层，前对中条山，下临黄河。'],['白日','bái rì','太阳。'],['依','yī','依傍、靠着。'],['欲','yù','想要得到某种东西或达到某种目的的愿望。'],['尽','jìn','消失；这里指太阳落山。'],['穷','qióng','尽，使达到极点。'],['千里目','qiān lǐ mù','眼界宽阔，能看到很远的地方。'],['更','gèng','再。']];
const quiz=[['“白日依山尽”中的“依”是什么意思？',['太阳','依傍、靠着','消失'],'依傍、靠着'],['想看到更远的风景，应该怎么做？',['再登上一层楼','马上回家','大声唱歌'],'再登上一层楼'],['《登鹳雀楼》的作者是谁？',['王之涣','李白','杜甫'],'王之涣']];
let learned=JSON.parse(localStorage.getItem('yuwen-learned')||'[]'), index=0, quizIndex=0;
const view=document.querySelector('#studyView');
function save(){localStorage.setItem('yuwen-learned',JSON.stringify(learned));updateProgress()}
function updateProgress(){const n=learned.length;document.querySelector('#progressText').textContent=`${n} / 12`;document.querySelector('#progressBar').style.width=`${Math.min(n/12*100,100)}%`}
function wordsView(){const [word,pinyin,definition]=words[index];const done=learned.includes('w'+index);view.innerHTML=`<div class="study-title"><h3>生字词卡片</h3><span class="counter">${index+1} / ${words.length}</span></div><div class="flashcard"><div class="character">${word}</div><div class="pinyin">${pinyin}</div><div class="definition">${definition}</div></div><div class="actions"><button class="secondary" id="prev">← 上一个</button><button class="primary" id="know">${done?'✓ 已掌握':'我会了！'}</button><button class="secondary" id="next">下一个 →</button></div>`;document.querySelector('#prev').onclick=()=>{index=(index+words.length-1)%words.length;wordsView()};document.querySelector('#next').onclick=()=>{index=(index+1)%words.length;wordsView()};document.querySelector('#know').onclick=()=>{if(!learned.includes('w'+index))learned.push('w'+index);save();wordsView()}}
function poemView(){view.innerHTML=`<div class="study-title"><h3>古诗朗读</h3><span class="counter">唐 · 王之涣</span></div><div class="poem-text"><span class="poem-title">登鹳雀楼</span>白日依山尽<br>黄河入海流<br>欲穷千里目<br>更上一层楼</div><div class="actions"><button class="primary" id="poemDone">${learned.includes('poem')?'✓ 我读过了':'我读一遍了！'}</button></div>`;document.querySelector('#poemDone').onclick=()=>{if(!learned.includes('poem'))learned.push('poem');save();poemView()}}
function meaningView(){view.innerHTML=`<div class="study-title"><h3>诗意小讲堂</h3><span class="counter">读懂每一句</span></div>${[['白日依山尽','太阳依傍着山慢慢落下去了。'],['黄河入海流','黄河水朝着大海奔流而去。'],['欲穷千里目','想要看到千里以外的风光。'],['更上一层楼','那就要再登上一层高楼。']].map(x=>`<div class="meaning-row"><b>${x[0]}</b><br>${x[1]}</div>`).join('')}<div class="actions"><button class="primary" id="meaningDone">${learned.includes('meaning')?'✓ 我明白了':'我明白了！'}</button></div>`;document.querySelector('#meaningDone').onclick=()=>{if(!learned.includes('meaning'))learned.push('meaning');save();meaningView()}}
function quizView(){const q=quiz[quizIndex];view.innerHTML=`<div class="study-title"><h3>小小挑战</h3><span class="counter">第 ${quizIndex+1} / ${quiz.length} 题</span></div><div class="quiz-question">${q[0]}</div><div class="quiz-options">${q[1].map(o=>`<button data-answer="${o}">${o}</button>`).join('')}</div>`;document.querySelectorAll('.quiz-options button').forEach(btn=>btn.onclick=()=>{const correct=btn.dataset.answer===q[2];btn.classList.add(correct?'correct':'wrong');if(correct&&!learned.includes('q'+quizIndex))learned.push('q'+quizIndex);save();setTimeout(()=>{quizIndex=(quizIndex+1)%quiz.length;quizView()},650)})}
function show(section){document.querySelectorAll('.lesson-card').forEach(x=>x.classList.toggle('active',x.dataset.section===section));({words:wordsView,poem:poemView,meaning:meaningView,quiz:quizView}[section])()}
document.querySelectorAll('.lesson-card').forEach(x=>x.onclick=()=>show(x.dataset.section));document.querySelector('#resetProgress').onclick=()=>{if(confirm('要重新开始今天的预习吗？')){learned=[];save();show('words')}};updateProgress();show('words');
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
